[build]
  command = "python app.py"
  publish = "build/"
  environment = { PYTHON_VERSION = "3.9.13" }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[functions]
  directory = "netlify/functions"
