[build]
  publish = "static"
  functions = "netlify/functions"
  command = "pip install -r requirements.txt"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[functions]
  directory = "netlify/functions"
